# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml
# This file: cloned from https://github.com/gruntjs/grunt/blob/master/appveyor.yml

# Build version format
version: "{build}"

# Test against this version of Node.js
environment:
  nodejs_version: "Stable"

build: off

clone_depth: 10

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install -g webdriver-manager
  - npm update -g webdriver-manager --versions.chrome=2.24 --versions.standalone=2.53.1
  - ps: $env:path = $env:appdata + "\npm;" + $env:path
  - npm install && npm install karma-ie-launcher

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584
  - ps: "npm --version # PowerShell" # Pass comment to PS for easier debugging
  - npm run tests.all && npm run build.prod.exp

cache: node_modules

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
